### ISSUE TITLE
Features with missing coordinate values should be null, rather than [null, null]

### ISSUE THREAD

**Issue by dontevenblink** [LoganSound/CopterFeeder#9]
Features with missing coordinate values should be `{ coordinates: null }`, rather than and array of nulls `{ coordinates: [null, null] }`.

I'm working on creating a geospatial index in the mongoDB ADSB collection to improve performance. Features with missing coordinate values written as `{ coordinates: [null, null] }` cause an indexing error from Mongo. A good solution this may be to write those cases as `{ coordinates: null }` instead, as indexing with `{ sparse: true }` seems to allow for null values to be skipped. If we go with this, once deployed I could go back and update all the legacy data.

**Comment by brauhausdc** [comment]
Should be fixed - specifically set the variable that holes the alt_geom to "None" (python's version of Null)

**Comment by brauhausdc** [comment]
Closing - but can reopen if it continues to be a problem.

**Comment by brauhausdc** [comment]
Not quote fixed yet

**Comment by brauhausdc** [comment]
Think this is fixed but waiting for Sam's OK.

**Comment by dontevenblink** [comment]
Seems fixed, to me! Thanks!

**Comment by brauhausdc** [comment]
Reopening long enough to merge in the Branch.
